### PR TITLE
Fix issue 20

### PR DESCRIPTION
**Pull request by za-arthur**
This bug was introduced by https://github.com/adjust/wltree/pull/15. It allows to have just one colon `:`. But `wltree`'s source code heavily relies on the fact that its delimiter consists of two colons `::`, for this we need to check both characters in advance.

Closes: #20

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
What is causing this Travis fail:
```
ltree_io.c:6:22: fatal error: postgres.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'ltree_io.o' failed
make: *** [ltree_io.o] Error 1
```

And given that Travis changes the structure in the near future, and GH Actions are installed, should we remove Travis entirely?

**Comment by za-arthur** [comment]
It fails for a while https://travis-ci.org/github/adjust/wltree/builds
Maybe it is something with the environment. Also it somehow uses wrong paths:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -DLOWER_NODE -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o ltree_io.o ltree_io.c
```
`/usr/include/postgresql/10/server` for PostgreSQL 9.6.

I think we can just drop Travis support instead of trying to fix, since tests pass on Github Actions.

**Comment by zilder** [comment]
Got some wierd result:
```
postgres=# select 'a:::b'::lquery;
   lquery    
-------------
 a:::b::*{0}
(1 row)
```

**Comment by za-arthur** [comment]
> Got some wierd result:

Thanks! I fixed this.

File: ltree_io.c [hunk 1]
```diff
@@ -90,35 +98,36 @@ ltree_in(PG_FUNCTION_ARGS)
...
 		}
-		else if (state == LTPRS_WAITDELIMEND)
+		else if (state == LTPRS_WAITDELIM)
 		{
-			if (charlen == 1 && t_iseq(ptr, NODE_DELIMITER_CHAR))
+			if (is_delimiter(ptr, charlen))
 			{
-				lptr->len = ptr - lptr->start - 1;
-				lptr->wlen--;
+				delimiter = true;
```
Comment (zilder) [inline ltree_io.c:121]: since we call `is_delimiter` in both cases, it would be shorter to do something like this:
```c
delimiter = is_delimiter(ptr, charlen);
if (state == LTPRS_WAITNAME)
{
    if (delimiter) { ... }
}
else if (state == LTPRS_WAITDELIM)
{
    if (delimiter) { ... }
}
```

**Review by zilder — COMMENTED** [review]
Overall looks good to me

File: ltree_io.c [hunk 2]
```diff
@@ -127,21 +136,28 @@ ltree_in(PG_FUNCTION_ARGS)
...
-		ptr += charlen;
-		lptr->wlen++;
-		pos++;
+		/*
+		 * wltree's delimiter is two characters, we need additional
+		 * increment here.
+		 */
+		if (delimiter)
+		{
+			ptr += charlen * 2;
```
[the remark this answers is not in the document]
Comment (za-arthur) [reply ltree_io.c]: Make sense! I added `NODE_DELIMITER_LEN`.

File: ltree_io.c [hunk 3]
```diff
@@ -40,7 +40,26 @@ typedef struct
...
 #define LTPRS_WAITDELIM 1
-#define LTPRS_WAITDELIMEND	2
+
+/*
+ * Check if the current character is delimiter. wltree's delimiter has multiple
+ * characters, we need to check all of them in advance.
+ *
+ * Returns true if sequential characters are equal to wltree's delimiter.
+ */
+static bool
```
[the remark this answers is not in the document]
Comment (za-arthur) [reply ltree_io.c]: Added

File: ltree_io.c (hunk 1 above)
Comment (za-arthur) [reply ltree_io.c]: Agree. I simplified the code to avoid multiple `is_delimiter` calls.
